[project]
name = "python-chat-igortrajic"
version = "0.1.0"
description = "python tcp chat"
readme = "README.md"
authors = [
    { name = "igortrajic", email = "iggetrajic@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "rich>=15.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.7",
]
